### PR TITLE
Add license summary

### PR DESCRIPTION
**Pull request by xylar**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
Linter is also broken when I run locally:
```
conda smithy recipe-lint .
Traceback (most recent call last):
  File "/home/xylar/miniconda3/bin/conda-smithy", line 10, in <module>
    sys.exit(main())
  File "/home/xylar/miniconda3/lib/python3.7/site-packages/conda_smithy/cli.py", line 554, in main
    args.subcommand_func(args)
  File "/home/xylar/miniconda3/lib/python3.7/site-packages/conda_smithy/cli.py", line 392, in __call__
    return_hints=True,
  File "/home/xylar/miniconda3/lib/python3.7/site-packages/conda_smithy/lint_recipe.py", line 697, in main
    results, hints = lintify(meta, recipe_dir, conda_forge)
  File "/home/xylar/miniconda3/lib/python3.7/site-packages/conda_smithy/lint_recipe.py", line 550, in lintify
    shellcheck_enabled = code.get("shellcheck", {}).get(
AttributeError: 'CommentedSeq' object has no attribute 'get'
```

**Comment by xylar** [comment]
I've traced the linting issue back to the empty `conda_forge.yaml`:
https://github.com/conda-forge/proj-data-feedstock/blob/master/conda-forge.yml
which doesn't seem to change when I rerender, either with the bot or locally.

**Comment by scopatz** [comment]
The linter failure is probably an issue with the comments or with some of the test code

**Comment by scopatz** [comment]
I am going to move build 0 to broken now

**Comment by xylar** [comment]
> The linter failure is probably an issue with the comments or with some of the test code

I don't think so, at least not directly.  I tried making a bunch of changes to `meta.yaml` and they had no effect.  The part of the linter that's causing the error has to do with reading `conda-forge.yaml`, as I mentioned above.  If `conda-forge.yaml` is essentially blank because of an error in the `meta.yaml`, then I suspect it would be due to more than just comments and shouldn't be related to the test code eihter.

**Comment by scopatz** [comment]
Please open an issue on conda-smithy!

**Pull request merged**
